# Generated by Django 4.2.11 on 2024-03-24 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opened_at', models.DateTimeField(blank=True, null=True)),
                ('identifier', models.CharField(blank=True, max_length=25, null=True, unique=True)),
                ('symbol', models.CharField(max_length=16)),
                ('side', models.CharField(choices=[('BUY', 'Buy'), ('SEL', 'Sell')], default='SEL', max_length=3)),
                ('volume', models.FloatField(blank=True, null=True)),
                ('open_price', models.FloatField(blank=True, null=True)),
                ('take_profit', models.FloatField(blank=True, null=True)),
                ('stop_loss', models.FloatField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('close_price', models.FloatField(blank=True, null=True)),
                ('commission', models.FloatField(blank=True, null=True)),
                ('swap', models.FloatField(blank=True, null=True)),
                ('profit', models.FloatField(blank=True, null=True)),
                ('reason', models.CharField(choices=[('TP', 'TP'), ('SL', 'SL')], default='TP', max_length=2)),
                ('market', models.CharField(choices=[('FX', 'Forex'), ('FT', 'Futures'), ('IN', 'Indices'), ('CR', 'Crypto')], default='FX', max_length=2)),
                ('rr', models.IntegerField(blank=True, null=True)),
                ('risk', models.IntegerField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, max_length=200)),
                ('link', models.URLField(blank=True)),
                ('image', models.ImageField(blank=True, upload_to='trades/images/%Y/%m/%d/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-opened_at'],
            },
        ),
        migrations.CreateModel(
            name='TradeLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='TradingAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(blank=True, max_length=25, null=True, unique=True)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('type', models.CharField(choices=[('REAL', 'Real'), ('CHAL', 'Challenge'), ('FUND', 'Funded')], default='REAL', max_length=4)),
                ('initial_balance', models.IntegerField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
