# Generated by Django 4.2.11 on 2024-03-25 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='links',
            field=models.TextField(blank=True, help_text='Each link from new line in the format: http://tradingview.com/', max_length=1024),
        ),
        migrations.AlterField(
            model_name='trade',
            name='reason',
            field=models.CharField(choices=[('TP', 'TP'), ('SL', 'SL')], max_length=2),
        ),
    ]
