# Generated by Django 4.2.10 on 2024-02-18 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tradingaccount',
            options={'ordering': ['-title']},
        ),
        migrations.AddIndex(
            model_name='tradingaccount',
            index=models.Index(fields=['-title'], name='trades_trad_title_bc6c7a_idx'),
        ),
    ]
