# Generated by Django 4.2.10 on 2024-02-18 17:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0002_alter_tradingaccount_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradingaccount',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tradingaccount',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
