# Generated by Django 4.2.11 on 2024-03-24 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0002_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='tradingaccount',
            name='trades_trad_title_bc6c7a_idx',
        ),
        migrations.AlterField(
            model_name='tradingaccount',
            name='identifier',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddConstraint(
            model_name='tradingaccount',
            constraint=models.UniqueConstraint(fields=('identifier', 'owner'), name='unique_tradingaccount_and_owner'),
        ),
    ]
