# Generated by Django 4.2.11 on 2024-03-24 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0003_remove_tradingaccount_trades_trad_title_bc6c7a_idx_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trade',
            options={},
        ),
        migrations.AlterModelOptions(
            name='tradingaccount',
            options={},
        ),
        migrations.AlterField(
            model_name='trade',
            name='identifier',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddConstraint(
            model_name='trade',
            constraint=models.UniqueConstraint(fields=('trading_account', 'identifier', 'owner'), name='unique_tradingaccount_and_owner_and_identifier'),
        ),
    ]
