# Generated by Django 4.2.10 on 2024-03-07 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0003_tradingaccount_created_at_tradingaccount_updated_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tradingaccount',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='tradingaccount',
            name='login',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='tradingaccount',
            name='password',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='tradingaccount',
            name='url',
            field=models.URLField(blank=True),
        ),
    ]
