# Generated by Django 4.2.10 on 2024-03-07 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0004_alter_tradingaccount_options_tradingaccount_login_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=25)),
                ('symbol', models.CharField(max_length=8)),
                ('opened_at', models.DateTimeField(blank=True, null=True)),
                ('volume', models.FloatField(blank=True, null=True)),
                ('side', models.CharField(choices=[('BUY', 'Buy'), ('SEL', 'Sell')], default='SEL', max_length=3)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('open_price', models.FloatField(blank=True, null=True)),
                ('close_price', models.FloatField(blank=True, null=True)),
                ('stop_loss', models.FloatField(blank=True, null=True)),
                ('take_profit', models.FloatField(blank=True, null=True)),
                ('swap', models.FloatField(blank=True, null=True)),
                ('commission', models.FloatField(blank=True, null=True)),
                ('reason', models.CharField(choices=[('TP', 'Take Profit'), ('SL', 'Stop Loss'), ('US', 'User')], default='TP', max_length=2)),
                ('market', models.CharField(choices=[('FX', 'Forex'), ('FT', 'Futures'), ('IN', 'Indices'), ('CR', 'Crypto')], default='FX', max_length=2)),
                ('rr', models.IntegerField(blank=True, null=True)),
                ('risk', models.IntegerField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, max_length=200)),
                ('link', models.URLField(blank=True)),
                ('image', models.ImageField(blank=True, upload_to='trades/images/%Y/%m/%d/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-opened_at'],
            },
        ),
    ]
