# Generated by Django 4.2.10 on 2024-03-07 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0005_trade'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='profit',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
