# Generated by Django 4.2.10 on 2024-03-07 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0006_trade_profit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tradingaccount',
            name='login',
        ),
        migrations.RemoveField(
            model_name='tradingaccount',
            name='password',
        ),
        migrations.RemoveField(
            model_name='tradingaccount',
            name='url',
        ),
        migrations.AlterField(
            model_name='trade',
            name='identifier',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AlterField(
            model_name='trade',
            name='reason',
            field=models.CharField(choices=[('TP', 'Take Profit'), ('SL', 'Stop Loss')], default='TP', max_length=2),
        ),
        migrations.AlterField(
            model_name='trade',
            name='symbol',
            field=models.CharField(max_length=16),
        ),
    ]
