# Generated by Django 4.2.10 on 2024-03-07 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0007_remove_tradingaccount_login_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='trading_account',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='trades.tradingaccount'),
            preserve_default=False,
        ),
    ]
