# Generated by Django 4.2.10 on 2024-03-10 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0009_trade_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradingaccount',
            name='identifier',
            field=models.CharField(blank=True, max_length=25),
        ),
    ]
