# Generated by Django 4.2.10 on 2024-03-14 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0011_alter_trade_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='reason',
            field=models.CharField(choices=[('TP', 'TP'), ('SL', 'SL')], default='TP', max_length=2),
        ),
    ]
