# Generated by Django 4.2.10 on 2024-03-14 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0012_alter_trade_reason'),
    ]

    operations = [
        migrations.CreateModel(
            name='TradeLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trades.trade')),
            ],
        ),
    ]
