# Generated by Django 4.2.10 on 2024-03-14 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0013_tradelink'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tradelink',
            name='post',
        ),
        migrations.AddField(
            model_name='tradelink',
            name='trade',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='trades.trade'),
            preserve_default=False,
        ),
    ]
