# Generated by Django 4.2.10 on 2024-03-14 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0014_remove_tradelink_post_tradelink_trade'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradelink',
            name='title',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
