# Generated by Django 4.2.10 on 2024-03-14 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0015_tradelink_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tradelink',
            name='title',
        ),
    ]
