# Generated by Django 4.2.10 on 2024-03-19 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0016_remove_tradelink_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='identifier',
            field=models.CharField(blank=True, max_length=25, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='tradingaccount',
            name='identifier',
            field=models.CharField(blank=True, max_length=25, null=True, unique=True),
        ),
    ]
